### ISSUE TITLE
老师，请教个问题

### ISSUE THREAD

**Issue by bestxwl0** [feng-li/talks#1]
2023 BUAA, 2020 ISF, Feature based Bayesian Forecast Model Averaging 这个目录下的pdf好像有损坏。

**Comment by feng-li** [comment]
[talk.pdf](https://github.com/feng-li/talks/files/14417796/talk.pdf)

我这里可以打开，不行你试一下这个版本。

**Comment by bestxwl0** [comment]
> [talk.pdf](https://github.com/feng-li/talks/files/14417796/talk.pdf)
> 
> 我这里可以打开，不行你试一下这个版本。

这个版本可以了，多谢老师！
